In [1]:
import numpy as np
import heapq

start = np.array([0, 0])
goal = np.array([5, 9])
grid = np.zeros((10, 10))
grid[:9, 1:3] = 1  # Creating some obstacles

path = np.zeros((len(grid), len(grid[0])))

class AStar:
    def __init__(self, start, goal, grid, path):
        self.start = start
        self.goal = goal
        self.grid = grid
        self.path = path
        self.open_list = []
        self.closed_list = set()
        self.came_from = {}

    def heuristic(self, position):
        # Manhattan distance to the goal
        return abs(position[0] - self.goal[0]) + abs(position[1] - self.goal[1])

    def valid_move(self, position):
        if (0 <= position[0] < self.grid.shape[0] and
            0 <= position[1] < self.grid.shape[1] and
            self.grid[position[0], position[1]] == 0):  # '0' means free space
            return True
        return False

    def reconstruct_path(self, current):
        moves = 0
        while current in self.came_from:
            self.path[current[0], current[1]] = 1
            current = self.came_from[current]
            moves += 1
        self.path[self.start[0], self.start[1]] = 1  # Mark the start position
        self.path[self.goal[0], self.goal[1]] = 1  # Mark the goal position
        return moves

    def astar(self):
        heapq.heappush(self.open_list, (0 + self.heuristic(self.start), 0, tuple(self.start)))

        while self.open_list:
            _, current_depth, current_pos = heapq.heappop(self.open_list)
            current_pos = np.array(current_pos)

            if np.array_equal(current_pos, self.goal):
                moves = self.reconstruct_path(tuple(self.goal))
                return moves

            self.closed_list.add(tuple(current_pos))

            # Explore neighbors (right, left, down, up)
            neighbors = [
                current_pos + np.array([0, 1]),  # Right
                current_pos + np.array([0, -1]),  # Left
                current_pos + np.array([1, 0]),  # Down
                current_pos + np.array([-1, 0]),  # Up
            ]

            for neighbor in neighbors:
                if not self.valid_move(neighbor) or tuple(neighbor) in self.closed_list:
                    continue

                tentative_g_score = current_depth + 1  # Cost is 1 for non-diagonal moves

                if tuple(neighbor) not in [i[2] for i in self.open_list] or tentative_g_score < current_depth:
                    self.came_from[tuple(neighbor)] = tuple(current_pos)
                    f_score = tentative_g_score + self.heuristic(neighbor)
                    heapq.heappush(self.open_list, (f_score, tentative_g_score, tuple(neighbor)))

        return False

# Run the A* algorithm
astar = AStar(start, goal, grid, path)
moves = astar.astar()

# Output the path matrix
print("Path matrix (0 means no path, 1 indicates the path):")
print(astar.path)

# Output the number of moves
print(f"Number of moves to reach the goal: {moves}")


Path matrix (0 means no path, 1 indicates the path):
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]]
Number of moves to reach the goal: 22
