In [2]:
import numpy as np

start = np.array([0, 0])
goal = np.array([5, 9])
grid = np.zeros((10, 10))
grid[:9, 1:3] = 1  # Creating some obstacles

path = np.zeros((len(grid), len(grid[0])))

class BFS:
    def __init__(self, start, goal, grid, path):
        self.pos = start
        self.pos_str = str(start.tolist())
        self.pos_depth = 0
        self.goal_str = str(goal.tolist())
        self.explored = {}
        self.not_explored = {}
        self.not_explored[self.pos_str] = 0
        self.grid = grid
        self.path = path

    def get_possible_moves(self):
        potential_moves = self.guarantee_potential_moves(self.pos)
        for move in potential_moves:
            if not self.valid_move(move):
                continue
            if str(move.tolist()) not in self.explored and str(move.tolist()) not in self.not_explored:
                self.not_explored[str(move.tolist())] = self.pos_depth + 1
        self.explored[self.pos_str] = 0

    def goal_found(self):
        if self.goal_str in self.not_explored:
            self.pos_str = self.goal_str
            self.pos = self.string_to_array(self.goal_str)
            self.pos_depth = self.not_explored.pop(self.goal_str)
            self.path[self.pos[0], self.pos[1]] = self.pos_depth
            return True
        return False

    def explore_next_move(self):
        sorted_not_explored = sorted(self.not_explored, key=self.not_explored.get, reverse=False)
        self.pos_str = sorted_not_explored[0]
        self.pos = self.string_to_array(self.pos_str)
        self.pos_depth = self.not_explored.pop(self.pos_str)
        self.path[self.pos[0], self.pos[1]] = self.pos_depth

    def guarantee_potential_moves(self, position):
        moves = [
            position + np.array([0, 1]),  # Right
            position + np.array([0, -1]),  # Left
            position + np.array([1, 0]),  # Down
            position + np.array([-1, 0])  # Up
        ]
        return moves

    def valid_move(self, position):
        if (0 <= position[0] < self.grid.shape[0] and
            0 <= position[1] < self.grid.shape[1] and
            self.grid[position[0], position[1]] == 0):  # '0' means free space
            return True
        return False

    def string_to_array(self, string_pos):
        return np.array(eval(string_pos))

# Run the BFS algorithm
bfs = BFS(start, goal, grid, path)

# Explore until the goal is found
while not bfs.goal_found():
    bfs.get_possible_moves()
    bfs.explore_next_move()

# Output the path matrix
print("Path matrix (0 means no path, positive numbers indicate steps taken):")
print(bfs.path)

# Output the number of moves required to reach the goal
print(f"Number of moves to reach the goal: {bfs.pos_depth}")



Path matrix (0 means no path, positive numbers indicate steps taken):
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0. 20.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0. 19. 20.  0.  0.  0.  0.  0.]
 [ 3.  0.  0. 18. 19. 20.  0.  0.  0.  0.]
 [ 4.  0.  0. 17. 18. 19. 20.  0.  0.  0.]
 [ 5.  0.  0. 16. 17. 18. 19. 20. 21. 22.]
 [ 6.  0.  0. 15. 16. 17. 18. 19. 20. 21.]
 [ 7.  0.  0. 14. 15. 16. 17. 18. 19. 20.]
 [ 8.  0.  0. 13. 14. 15. 16. 17. 18. 19.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]]
Number of moves to reach the goal: 22
