In [1]:
import numpy as np

start = np.array([0, 0])
goal = np.array([5, 9])
grid = np.zeros((10, 10))
grid[:9, 1:3] = 1  # Creating some obstacles

path = np.zeros((len(grid), len(grid[0])))

class DFS:
    def __init__(self, start, goal, grid, path):
        self.start = start
        self.goal = goal
        self.grid = grid
        self.path = path
        self.found = False

    def valid_move(self, position):
        if (0 <= position[0] < self.grid.shape[0] and
            0 <= position[1] < self.grid.shape[1] and
            self.grid[position[0], position[1]] == 0 and
            self.path[position[0], position[1]] == 0):  # '0' means free space and not visited
            return True
        return False

    def dfs(self, position, depth):
        if not self.valid_move(position) or self.found:
            return False

        self.path[position[0], position[1]] = depth

        if np.array_equal(position, self.goal):
            self.found = True
            return True

        # Explore neighbors (right, left, down, up)
        moves = [
            position + np.array([0, 1]),  # Right
            position + np.array([1, 0]),  # Down
            position + np.array([0, -1]),  # Left
            position + np.array([-1, 0]),  # Up
        ]

        for move in moves:
            if self.dfs(move, depth + 1):
                return True

        # Backtrack
        self.path[position[0], position[1]] = 0
        return False

# Run the DFS algorithm
dfs = DFS(start, goal, grid, path)
dfs.dfs(start, 1)

# Output the path matrix
print("Path matrix (0 means no path, positive numbers indicate steps taken):")
print(dfs.path)

# Output the number of moves
path_steps = dfs.path[dfs.path > 0]
print(f"Number of moves to reach the goal: {len(path_steps)}")


Path matrix (0 means no path, positive numbers indicate steps taken):
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 6.  0.  0. 41. 42. 43. 44. 45. 46. 47.]
 [ 7.  0.  0. 40. 39. 38. 37. 36. 35. 34.]
 [ 8.  0.  0. 27. 28. 29. 30. 31. 32. 33.]
 [ 9.  0.  0. 26. 25. 24. 23. 22. 21. 20.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
Number of moves to reach the goal: 47
